### PR TITLE
Add support to update tasks.

### PR DESCRIPTION
**Pull request by dmitshur**
~~**DO NOT MERGE.**~~ Ready to review and merge.

This is a WIP PR to add support for update tasks method. There are some TODOs left, and some thinking before merging.

Since this is the first non-read-only method, there is some API design and thinking to be done.

This PR is primarily to get any review comments about the write API decisions.

I went with a slightly different approach compared to go-github. Instead of trying to reuse the same struct for sending update operations as for getting values, I created a separate struct that is dedicated to the updates. It only has relevant fields, and they're pointers to allow setting only the desired fields. I'm curious what @willnorris would think of this.

### CODE REVIEW

**Comment by willnorris** [comment]
> I went with a slightly different approach compared to go-github. Instead of trying to reuse the same struct for sending update operations as for getting values, I created a separate struct that is dedicated to the updates. It only has relevant fields, and they're pointers to allow setting only the desired fields. I'm curious what @willnorris would think of this.

In theory, this would prevent you from doing things like taking a response from one API call, and using it as input to another API call. Instead, you'd have to do the transfer between the read struct and the write struct.  In practice, I don't know how likely this kind of requirement actually is.  It would depend very much on the specific API.  There's also the downside that for an API that has lots of data types, this up to doubles that.  Less of an issue for small APIs, not great for something the size of GitHub.

I've also kinda been wanting to revisit the question posed at https://github.com/google/go-github/issues/19#issuecomment-229294222.  It's certainly too late to make that kind of change in go-github, but I think it could be interesting for other clients.  Would it be possible to use a field mask to limit which fields are passed in an API call, but in a way that preserves type safety?  Something akin to:

``` go
func (t *Task) Mask(fields ...string) *Task {
    // filter t to only contain values for specified fields
}
```

Which you would use sort of like:

``` go
t := &Task {
    Name: "new name",
}
client.UpdateTask(1, t.Mask("name"))
```

This differs from [Quinn's original proposal](https://github.com/google/go-github/issues/19#issuecomment-22151321) in that Mask returns a `*Task` rather than a `map[string]interface{}`, which was the type safety I mentioned in my comment on that thread.  As before, the trick here is dealing with zero values.  I haven't given this enough thought to consider whether this masking technique actually helps us with that, or if we come full circle back to the original problem.

**Comment by willnorris** [comment]
One additional thing I like about the above approach is that the field masking is completely optional in cases where you don't need it.  For example, if you already had a fully populated struct that could be passed as-is to the API without masking anything, you could still pass it directly to `UpdateTask`.  The `Mask` method only needs to be called when you have zero values in the struct that shouldn't be passed.

**Comment by dmitshur** [comment]
Thanks for sharing your feedback, Will. 👍  I'll think more about this.

> For example, if you already had a fully populated struct that could be passed as-is to the API without masking anything, you could still pass it directly to `UpdateTask`.  The `Mask` method only needs to be called when you have zero values in the struct that shouldn't be passed.

I think that you would want to zero/exclude values you don't mean to update even if you happen to have them already, primarily for the following reason:

> When using this method, it is best to specify only those fields you wish to change, or **else you may overwrite changes made by another user** since you last retrieved the task.

It's also less bandwidth used (very insignificantly perhaps).

**Comment by dmitshur** [comment]
> As before, the trick here is dealing with zero values.  I haven't given this enough thought to consider whether this masking technique actually helps us with that, or if we come full circle back to the original problem.

Yep, you'd need to be able to emit some struct that avoids the zero values. Either by using a struct with pointers, or by dynamically creating an `map[string]interface{}`. It's possible, but would require some thinking and iterating.

My plan is as follows. I've considered all of the feedback in this thread, and so far I don't have concrete immediate ideas for improvement that I want to incorporate before this PR is merged. I think this current approach is a good, simple starting point. However, I will add a note to the README stating that the API is not yet 100% final version, and may have some breaking changes as we find better ways of doing things (see 4db778d893a789ae75583b8c8118d0d767363008).

Since this library is not yet used by many clients (I'm the first person that had a need for doing write actions), I will merge this and we can consider API changes in the future. I think it'll make it easier to evaluate alternative API ideas when thinking of it as a diff to the current working simple solution (in this PR).

**Comment by dmitshur** [comment]
I've addressed all outstanding TODOs. I've merged this now since it's ready, this is a low activity repo and there were no objections. If there's any additional comments, we can follow up.

You can see an example of the update task API (which was added in this PR) used [here](https://github.com/shurcooL/issues/commit/d0a88217cfdfb095d2eff376d87e7270d6fa5a83#diff-8b97d003b0e1a84dc0b6c1e18b9f9636R291). I'm very happy to update my code there as needed if there any future API changes that we decide to adopt.

**Pull request merged**
